### ISSUE TITLE
Issues on iPhone

### ISSUE THREAD

**Issue by draperunner** [draperunner/wcg-client#3]
Apparently only the background color is showing on iPhone, on both Safari and Chrome. Hard for me to debug, as I don't have an iPhone.

![slack for ios upload](https://cloud.githubusercontent.com/assets/4339443/20650588/4f59cdec-b4d2-11e6-9bd2-9506b5f79be0.jpg)

Quick solution: buy an Android phone.

**Comment by kandersk** [comment]
Was able to get the mobile web page to load when simulating iphone
<img width="418" alt="screenshot 2018-10-31 at 09 23 13" src="https://user-images.githubusercontent.com/22399935/47791107-481db100-dcef-11e8-8f84-30fa6723a86e.png">

**Comment by draperunner** [comment]
Thanks! And happy Hacktober! 😁
